version: "3"
services:
  front:
    build:
      context: .
      dockerfile: ./front/lettuce-meat/Dockerfile
    ports: ["3000:3000"]
    volumes: [./front:/front]
  back:
    build:
      context: .
      dockerfile: ./back/Dockerfile
    ports: ["5000:5000"]
    volumes: [./back:/back]